site_name: Java Learning Platform
site_description: 'A comprehensive resource for Java developers covering core concepts to advanced microservices architecture'
site_author: 'Your Organization'
site_url: 'https://yourusername.github.io/java-learning'

# Repository
repo_name: 'yourusername/java-learning'
repo_url: 'https://github.com/yourusername/java-learning'
edit_uri: 'edit/main/docs/'

# Copyright
copyright: 'Copyright &copy; 2023 Your Organization'

# Theme
theme:
  name: material
  language: en
  palette:
    primary: 'indigo'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/yourusername'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/yourusername'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
plugins:
  - search:
      lang: en
  - macros

# Navigation
nav:
  - Home: index.md
  - Java Core:
      - 'Basic Concepts': 'java/basic-concepts.md'
      - 'Basics': 'java/java-basics.md'
      - 'OOP': 'java/java-oop.md'
      - 'Collections': 'java/java-collections.md'
      - 'Exceptions': 'java/java-exceptions.md'
      - 'Exception Handling': 'java/java-exception-handling.md'
      - 'Multithreading': 'java/java-multithreading.md'
      - 'Concurrency': 'java/java-concurrency.md'
      - 'I/O': 'java/java-io.md'
      - 'Streams & Lambdas': 'java/java-streams-lambdas.md'
      - 'Generics': 'java/java-generics.md'
      - 'Memory Management': 'java/java-memory-management.md'
      - 'Testing': 'java/java-testing.md'
  - Spring Boot:
      - 'Core Concepts': 'spring-boot/spring-boot-core-concepts.md'
      - 'Starter': 'spring-boot/spring-boot-starter.md'
      - 'REST API': 'spring-boot/spring-boot-rest-api.md'
      - 'Data Access': 'spring-boot/spring-boot-data-access.md'
      - 'Security': 'spring-boot/spring-boot-security.md'
      - 'Testing': 'spring-boot/spring-boot-testing.md'
      - 'Actuator': 'spring-boot/spring-boot-actuator.md'
      - 'Deployment': 'spring-boot/spring-boot-deployment.md'
      - 'AOP': 'spring-boot/spring-boot-aop.md'
      - 'Configuration': 'spring-boot/spring-boot-configuration.md'
      - 'Spring Data JPA': 'spring-boot/spring-data-jpa.md'
      - 'Spring Data MongoDB': 'spring-boot/spring-data-mongo.md'
      - 'Kafka Integration': 'spring-boot/spring-kafka-integration.md'
      - 'Spring AI': 'spring-boot/spring-ai.md'
      - 'Best Practices': 'spring-boot/spring-boot-best-practices.md'
  - Microservices:
      - 'Basics': 'microservices/microservices-basics.md'
      - 'Communication': 'microservices/microservices-communication.md'
      - 'Service Discovery': 'microservices/microservices-discovery.md'
      - 'Resilience': 'microservices/microservices-resilience.md'
      - 'API Gateway': 'microservices/microservices-api-gateway.md'
      - 'Security': 'microservices/microservices-security.md'
      - 'Monitoring': 'microservices/microservices-monitoring.md'
      - 'Deployment': 'microservices/microservices-deployment.md'
      - 'Testing': 'microservices/microservices-testing.md'
      - 'Best Practices': 'microservices/microservices-best-practices.md'
      - 'Saga Pattern': 'microservices/saga-pattern.md'
      - 'CQRS Pattern': 'microservices/cqrs-pattern.md'
      - 'Platform Architecture': 'microservices/platform-architecture.md'
  - Kubernetes:
      - 'Basics': 'kubernetes/kubernetes-basics.md'
      - 'Deployment': 'kubernetes/kubernetes-deployment.md'
      - 'Services': 'kubernetes/kubernetes-services.md'
      - 'Config & Secrets': 'kubernetes/kubernetes-config-secrets.md'
      - 'Storage': 'kubernetes/kubernetes-storage.md'
      - 'Scaling': 'kubernetes/kubernetes-scaling.md'
      - 'Monitoring': 'kubernetes/kubernetes-monitoring.md'
      - 'Security': 'kubernetes/kubernetes-security.md'
      - 'Networking': 'kubernetes/kubernetes-networking.md'
      - 'Troubleshooting': 'kubernetes/kubernetes-troubleshooting.md'
      - 'Best Practices': 'kubernetes/kubernetes-best-practices.md'
  - Design Patterns:
      - 'Principles': 'design-patterns/design-patterns-principles.md'
      - 'Best Practices': 'design-patterns/design-patterns-best-practices.md'
      - 'J2EE Patterns': 'design-patterns/design-patterns-j2ee.md'
      - 'Behavioral Patterns': 'design-patterns/design-patterns-behavioral.md'
      - 'Structural Patterns': 'design-patterns/design-patterns-structural.md'
      - 'Creational Patterns': 'design-patterns/design-patterns-creational.md'
  - Reference:
      - 'Deployment Guide': 'deployment-guide.md'
      - 'Search Implementation': 'search-implementation.md'
  - About:
      - 'Feedback': 'feedback.md'
      - 'Contributing': 'CONTRIBUTING.md'
      - 'License': 'LICENSE.md' 